/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 00:52:26 GMT 2019
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;

public class OrderItemTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OrderItem orderItem0 = new OrderItem("#.00", 0.0, 0);
      orderItem0.setCount((-4645));
      orderItem0.PrintOrderItem();
      assertEquals((-4645), orderItem0.getCount());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OrderItem orderItem0 = new OrderItem("#.00", 0.0, 0);
      int int0 = orderItem0.getCount();
      assertEquals(0.0, orderItem0.getPaymentPrice(), 0.01);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      OrderItem orderItem0 = new OrderItem("N'", 674.43377092, (-577));
      double double0 = orderItem0.getAmount();
      assertEquals((-389148.28582084004), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      OrderItem orderItem0 = new OrderItem("N'", 674.43377092, (-577));
      double double0 = orderItem0.getPaymentPrice();
      assertEquals(674.43377092, double0, 0.01);
      assertEquals((-389148.28582084004), orderItem0.getAmount(), 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      OrderItem orderItem0 = new OrderItem("N'", 674.43377092, (-577));
      orderItem0.setPaymentPrice((-577));
      assertEquals((-577.0), orderItem0.getPaymentPrice(), 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      OrderItem orderItem0 = new OrderItem("N'", 674.43377092, (-577));
      orderItem0.setProductName("N'");
      assertEquals((-389148.28582084004), orderItem0.getAmount(), 0.01);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      OrderItem orderItem0 = new OrderItem("#.00", 0.0, 0);
      orderItem0.getProductName();
      assertEquals(0.0, orderItem0.getPaymentPrice(), 0.01);
      assertEquals(0, orderItem0.getCount());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      OrderItem orderItem0 = new OrderItem("#.00", 0.0, 0);
      String string0 = orderItem0.PrintOrderItem();
      assertEquals("#.00\t.00\t0\t.00", string0);
  }
}
