/*
 * This file was automatically generated by EvoSuite
 * Sat Oct 26 00:51:14 GMT 2019
 */

package net.mooctest;

import org.junit.Test;
import static org.junit.Assert.*;

public class RoomTypeTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      boolean boolean0 = RoomType.isRoomType((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      boolean boolean0 = RoomType.isRoomType("Deluxe Room");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      boolean boolean0 = RoomType.isRoomType("Advanced Room");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      boolean boolean0 = RoomType.isRoomType("Standard Room");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RoomType roomType0 = new RoomType();
  }
}
